defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"
  authenticators:
    portal_tron:
      authenticator: "Mongoid"
      class: "CASino::MongoidAuthenticator"
      options:
        database_url: "mongodb://localhost:27017/portal_tron"
        collection: "users"
        username_column: "username"
        password_column: "password"
        pepper: "pepper" # optional
        extra_attributes:
          email: "email_database_column"
          fullname: "displayname_database_column"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
